apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: backend  # Must match the labels in the pod template
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gestion_commande_mern-backend:latest
        ports:
        - containerPort: 5000  # Expose port 5000 for the backend service
        env:
        - name: MONGO_URI
          value: mongodb://mongo-service:27017/gestion-commande_MERN  # MongoDB connection string
        resources:
          requests:
            memory: "256Mi"  # Minimum memory required
            cpu: "500m"      # Minimum CPU required
          limits:
            memory: "512Mi"  # Maximum memory allowed
            cpu: "1000m"     # Maximum CPU allowed
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend  # Match the app label of the pods
  ports:
  - protocol: TCP
    port: 5000       # Port exposed by the service
    targetPort: 5000 # Port exposed by the container
  type: ClusterIP    # Internal service (not accessible from outside the cluster)
