apiVersion: v2
name: gestion-commande-mern
description: A Helm chart for deploying the MERN stack application
type: application
version: 0.1.0
appVersion: "1.0"  # Version of the application
keywords:
  - mern
  - node
  - mongo
  - react
  - helm
  - docker
home: https://example.com # Homepage for your app
sources:
  - https://github.com/example/gestion-commande-mern # GitHub repo or other sources

maintainers:
  - name: Your Name
    email: your.email@example.com

icon: https://example.com/icon.png # Optional: Add an icon URL to represent the chart

dependencies:
  - name: mongodb
    version: "16.4.0"
    repository: "https://charts.bitnami.com/bitnami"
  - name: nginx
    version: "18.3.5"
    repository: "https://charts.bitnami.com/bitnami"
